### ISSUE TITLE
it seems like you deployed the code to GIt but did not commit and push the source

### ISSUE THREAD

**Issue by iabbassensamir** [devenparekh/Software-Development-Project-Fall-2020#1]

**Comment by devenparekh** [comment]
i watched a video showing us how to push the code from command line using the react js code to github. i have uploaded the assignment 1 that was due yesterday which has all the screenshots of the steps that showed me that it has uploaded everything. i tried clicking on the link and it gave me access to the react page too. So, can you please tell me as to what i should do to push the source?
